### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [KamikadzeBull/Cube#1]
1. Для фиксированного набора значений в Джаве принято использоват перечисления (`enum`). Направления поворота, цвета и стороны лучше кодировать ими. 
2. Не очень понятна нотация аргументов в  `cubeRotation`. По-моему, можно совершить 6 разных поворотов кубика: вокруг трёх осей в два разных направления (3 х 2 = 6)
3. Нет метода для перемешивания кубика
4. Вместо метода получения внутреннего массива лучше определить геттер, позволяющий прочитать цвет конкретной ячейки и метод equals для сравнения двух кубиков (например, в тестах). Если вы возвращаете ссылку на внутренний массив, то клиент вашего класса может изменить состояние кобика минуя API вашего класса.
5. `nearSidesID` лучше сделать приватным статическим полем, а не каждый раз создавать массив в статическом методе.
6. Вместо метода `show` лучше переопределить стандартный `toString`, возвращающий то, что вы печатаете.
7. С конструктором от трёхмерного массива та же самая проблема, что и в п. 4. Плюс можно изначально создать некорректный кубик. Поскольку вы его активно используете в тестах, лучше сделать этот конструктор package-private, а не публичным (кстати, ваш код лучше бы поместить в пакет)

**Comment by gagarski** [comment]
8. В `layerRotation` много копипасты. Нельзя ли избавиться от неё, давайте попробуем подумать на занятии.

**Comment by KamikadzeBull** [comment]
@gagarski , сделано!
